version: '3.8'

services:
  crypto-rebalancer:
    build: .
    container_name: crypto-rebalancer
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      # Mount logs directory to persist logs outside container
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "-v", "grep", "|", "grep", "node"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"